const consultants = [
  {
    id: 1,
    name: "サンプル太郎",
    image: "https://images.unsplash.com/photo-1539314171919-908b0cd96f03?crop=entropy&w=840&h=840&fit=crop",
    status: { key: "online", title: "オンライン" },
    // gender: "男",
    age: 35,
    numOfThunks: 125,
    numOfComments: 13,
    introduction: "職場の人間関係の悩みなどをよく相談に乗っています。",
  },
  {
    id: 12,
    name: "サンプル男爵",
    image: "https://images.unsplash.com/photo-1515709980177-7a7d628c09ba?crop=entropy&w=840&h=840&fit=crop",
    status: { key: "offline", title: "オフライン" },
    // gender: "女",
    age: 35,
    numOfThunks: 125,
    numOfComments: 13,
    introduction: "職場の人間関係の悩みなどをよく相談に乗っています。職場の人間関係の悩みなどをよく相談に乗っています。",
  },
  {
    id: 123,
    name: "サンプル伯爵",
    image: "https://images.unsplash.com/photo-1490367532201-b9bc1dc483f6?crop=entropy&w=840&h=840&fit=crop",
    status: { key: "online", title: "オンライン" },
    // gender: "男",
    age: 35,
    numOfThunks: 125,
    numOfComments: 13,
    introduction: "職場の人間関係の悩みなどをよく相談に乗っています。",
  },
  {
    id: 1234,
    name: "サンプル人民共和国",
    image: "https://images.unsplash.com/photo-1536303006682-2ee36ba49592?crop=entropy&w=840&h=840&fit=crop",
    status: { key: "online", title: "オフライン" },
    // gender: "女",
    age: 35,
    numOfThunks: 125,
    numOfComments: 13,
    introduction: "",
  },
  {
    id: 12345,
    name: "サンプル１２３４１２３４１２３４１２３４世",
    image: "https://images.unsplash.com/photo-1491336477066-31156b5e4f35?crop=entropy&w=840&h=840&fit=crop",
    status: { key: "online", title: "オンライン" },
    // gender: "男",
    age: 35,
    numOfThunks: 125,
    numOfComments: 13,
    introduction: "職場の人間関係",
  },
];

export default consultants;


export const fullConsultants = {
  "1": {
    id: 1,
    name: "サンプル太郎",
    image: "https://images.unsplash.com/photo-1539314171919-908b0cd96f03?crop=entropy&w=840&h=840&fit=crop",
    status: { key: "online", title: "オンライン" },
    // gender: "男",
    age: 35,
    numOfThunks: 125,
    numOfComments: 13,
    introduction: "職場の人間関係の悩みなどをよく相談に乗っています。",
    features: {
      4: "黙って聞きます",
      6: "質問少なめ",
      8: "声低め",
      17: "O型",
      20: "話を聞くのが好き",
    },
    genreOfWorries: {
      0: "仕事",
      3: "恋愛",
    },
    scaleOfWorries: {
      1: "軽い悩み",
      2: "雑談",
      5: "友達感覚で話したい",
    },
    worriesToSympathize: {
      2: "不倫",
      10: "子供思春期",
      26: "体",
    },
    full: true,
  },
  "12": {
    id: 12,
    name: "サンプル男爵",
    image: "https://images.unsplash.com/photo-1515709980177-7a7d628c09ba?crop=entropy&w=840&h=840&fit=crop",
    status: { key: "offline", title: "オフライン" },
    // gender: "女",
    age: 35,
    numOfThunks: 125,
    numOfComments: 13,
    introduction: "職場の人間関係の悩みなどをよく相談に乗っています。職場の人間関係の悩みなどをよく相談に乗っています。",
    features: {
      4: "黙って聞きます",
      6: "質問少なめ",
      8: "声低め",
      17: "O型",
      20: "話を聞くのが好き",
    },
    genreOfWorries: {
      0: "仕事",
      3: "恋愛",
    },
    scaleOfWorries: {
      1: "軽い悩み",
      2: "雑談",
      5: "友達感覚で話したい",
    },
    worriesToSympathize: {
      2: "不倫",
      10: "子供思春期",
      26: "体",
    },
    full: true,
  },
  "123": {
    id: 123,
    name: "サンプル伯爵",
    image: "https://images.unsplash.com/photo-1490367532201-b9bc1dc483f6?crop=entropy&w=840&h=840&fit=crop",
    status: { key: "online", title: "オンライン" },
    // gender: "男",
    age: 35,
    numOfThunks: 125,
    numOfComments: 13,
    introduction: "職場の人間関係の悩みなどをよく相談に乗っています。",
    features: {
      4: "黙って聞きます",
      6: "質問少なめ",
      8: "声低め",
      17: "O型",
      20: "話を聞くのが好き",
    },
    genreOfWorries: {
      0: "仕事",
      3: "恋愛",
    },
    scaleOfWorries: {
      1: "軽い悩み",
      2: "雑談",
      5: "友達感覚で話したい",
    },
    worriesToSympathize: {
      2: "不倫",
      10: "子供思春期",
      26: "体",
    },
    full: true,
  },
  "1234": {
    id: 1234,
    name: "サンプル人民共和国",
    image: "https://images.unsplash.com/photo-1536303006682-2ee36ba49592?crop=entropy&w=840&h=840&fit=crop",
    status: { key: "online", title: "オンライン" },
    // gender: "女",
    age: 35,
    numOfThunks: 125,
    numOfComments: 13,
    introduction: "",
    features: {
      4: "黙って聞きます",
      6: "質問少なめ",
      8: "声低め",
      17: "O型",
      20: "話を聞くのが好き",
    },
    genreOfWorries: {
      0: "仕事",
      3: "恋愛",
    },
    scaleOfWorries: {
      1: "軽い悩み",
      2: "雑談",
      5: "友達感覚で話したい",
    },
    worriesToSympathize: {
      2: "不倫",
      10: "子供思春期",
      26: "体",
    },
    full: true,
  },
  "12345": {
    id: 12345,
    name: "サンプル１２３４１２３４１２３４１２３４世",
    image: "https://images.unsplash.com/photo-1491336477066-31156b5e4f35?crop=entropy&w=840&h=840&fit=crop",
    status: { key: "online", title: "オンライン" },
    // gender: "男",
    age: 35,
    numOfThunks: 125,
    numOfComments: 13,
    introduction: "職場の人間",
    features: {
      4: "黙って聞きます",
      6: "質問少なめ",
      8: "声低め",
      17: "O型",
      20: "話を聞くのが好き",
    },
    genreOfWorries: {
      0: "仕事",
      3: "恋愛",
    },
    scaleOfWorries: {
      1: "軽い悩み",
      2: "雑談",
      5: "友達感覚で話したい",
    },
    worriesToSympathize: {
      2: "不倫",
      10: "子供思春期",
      26: "体",
    },
    full: true,
  }
};

export const profile = {
  id: 888,
  name: "けんさん",
  image: "https://otapick.com/media/member_images/2_18/600_600_102400.jpg",
  status: { key: "talking", title: "オフライン" }, // or {key: "offline", title: "オフライン"} or {key: "talking", title: "会話中"}
  // gender: "男",
  age: 21,
  numOfThunks: 0,
  // numOfComments: 0,
  plan: { key: "free", title: "無料" }, // or {key: "pro", title: "PRO"}
  introduction: "職場の人間関係の悩みなどをよく相談に乗っています。",
  features: {
    4: "黙って聞きます",
    6: "質問少なめ",
    8: "声低め",
    17: "O型",
    20: "話を聞くのが好き",
  },
  genreOfWorries: {
    0: "仕事",
    3: "恋愛",
  },
  scaleOfWorries: {
    1: "軽い悩み",
    2: "雑談",
    5: "友達感覚で話したい",
  },
  worriesToSympathize: {
    2: "不倫",
    10: "子供思春期",
    26: "体",
  },
  all: true,

  me: true,
  full: 500,
  point: 0,
  privacyName: "kensan",
  privacyImage: "https://otapick.com/media/member_images/2_6/600_600_102400.jpg",
  birthday: {
    text: "1998年9月14日",
    year: 1998,
    month: 9,
    day: 14,
  }
};